### PR TITLE
Add Windows support, remove vulnerabilities

### PR DESCRIPTION
**Pull request by erkstruwe**
Hi!

I added a small change to make the package support multi-line responses on Windows machines. Additionally, I ran `npm update` and `npm audit fix` to remove ~40k vulnerabilities. This will most likely close all open pull requests created by dependabot as well.

Since I don't have a Linux machine set up, I couldn't run the `build` script. Could you please run that, make another commit with changed files and republish on npm? Much appreciated!

Also, I changed version to `0.1.0` to obey semantic versioning rules.

### CODE REVIEW

**Comment by pandomic** [comment]
@erkstruwe thank you for your contribution. Will will try to review the PR shortly

**Review by dnbjn — CHANGES_REQUESTED** [review]
@erkstruwe Can you update the package version in **src/main/js/constants.js**?

**Comment by erkstruwe** [comment]
Yes, done. Thanks for your review.

**Review by dnbjn — CHANGES_REQUESTED** [review]
The tests are still failing. I noticed we specify the version in build.gradle and Constants.java.

**Comment by erkstruwe** [comment]
Oh, alright. I'm a total JS guy, don't know what I'm doing in terms of Java... Tests are working, though.

**Review by dnbjn — APPROVED** [review]

**Pull request merged**
